version: "3.3"

services:
  db:
    image: postgres:13
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - main
  web:
    build: .
    restart: always
    command: poetry run python run.py
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - main
volumes:
  postgres_data:
networks:
  main: